name: Update README

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: Felipe-Henrique-Dev/github-readme-repo-list@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

